default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: todo_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: todo_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: todo_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST