default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: d65s4lrja5g1pb
  username: dzzsxncmddqejh
  password: <%= ENV['a723827fab99a5a629aa1912eae3d482054cd6a42772c4f3f948e79c75d9ff7f'] %>
  url: <%= ENV['postgres://dzzsxncmddqejh:a723827fab99a5a629aa1912eae3d482054cd6a42772c4f3f948e79c75d9ff7f@ec2-54-225-88-199.compute-1.amazonaws.com:5432/d65s4lrja5g1pb'] %>